trigger:
  branches:
    include:
      - refs/tags/release

pool: "Cashflows RHEL8 Pool"

parameters:
- name: createRelease
  displayName: Create GitHub Release
  type: boolean
  default: false

variables:
  ${{ if eq(variables['Build.Reason'], 'Manual') }}:
    createRelease: ${{ parameters.createRelease }}
  ${{ else }}:
    createRelease: true
  nodeVersion: '14.x'
  releaseVersionMajorMinor: '1.0'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0 
      displayName: 'Install Node ${{ variables.nodeVersion }}'
      inputs:
        versionSpec: '${{ variables.nodeVersion }}'
    - task: Npm@1
      displayName: 'Npm Install'
      inputs:
        command: 'install'
    - task: Npm@1
      displayName: 'Npm Version'
      inputs:
        command: 'custom'
        customCommand: 'version'
    - task: Npm@1
      displayName: 'Npm Build'
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: Npm@1
      displayName: 'Npm Test'
      inputs:
        command: 'custom'
        customCommand: 'run test'
    - ${{ if eq(variables['createRelease'], 'True') }}:
      - task: CopyFiles@2
        displayName: 'Copy Dist Folder'
        inputs:
          contents: 'dist/**'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - publish: '$(Build.ArtifactStagingDirectory)/dist'
        displayName: 'Publish Dist Folder'
        artifact: dist

- ${{ if eq(variables['createRelease'], 'True') }}:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops
  - stage: Release
    dependsOn: Build
    jobs:
    - job: ReleaseGitHub
      variables:
        revision: $[ counter(variables['releaseVersionMajorMinor' ], 1)]
        version: ${{ variables['releaseVersionMajorMinor'] }}.$(revision)
      steps:
      - task: PowerShell@2
        displayName: 'Print Version'
        name: Version
        inputs:
          targetType: 'inline'
          script: |
            echo "Version: $(version)"
      - download: current
        artifact: dist
      - task: GitHubRelease@0
        displayName: 'Create GitHub Release'
        inputs:
          gitHubConnection: cashflows-public-Core
          repositoryName: 'cashflows/cashflows-clientlib-js'
          action: 'create'
          title: Release $(version)
          tagSource: manual
          tag: release-v$(version)
          assets: |
            $(Pipeline.Workspace)/dist/**
